# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CompletedTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(472, 710)
        Dialog.setMinimumSize(QtCore.QSize(472, 710))
        Dialog.setMaximumSize(QtCore.QSize(472, 710))
        Dialog.setStyleSheet("background-color: rgb(68, 134, 255);")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 451, 421))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(127)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 440, 451, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 540, 451, 161))
        self.frame_2.setStyleSheet("background-color: rgb(51, 100, 191);\n"
"border: 5px;\n"
"border-color: rgb(51, 100, 191);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textEdit_27 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_27.setGeometry(QtCore.QRect(10, 10, 431, 101))
        self.textEdit_27.setStyleSheet("border: 2px solid rgb(228, 232, 235);\n"
"border-left-color: rgb(85, 170, 255);\n"
"border-bottom-color: rgb(85, 170, 255);\n"
"\n"
"\n"
"")
        self.textEdit_27.setObjectName("textEdit_27")
        self.textEdit_28 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_28.setGeometry(QtCore.QRect(110, 120, 331, 31))
        self.textEdit_28.setStyleSheet("border: 2px solid rgb(51, 100, 191);\n"
"border-top-color:  rgb(85, 170, 255);\n"
"border-right-color: rgb(228, 232, 235);\n"
"border-left-color:  rgb(85, 170, 255);\n"
"border-bottom-color: rgb(228, 232, 235);\n"
"\n"
"")
        self.textEdit_28.setObjectName("textEdit_28")
        self.exit_Button = QtWidgets.QPushButton(self.frame_2)
        self.exit_Button.setGeometry(QtCore.QRect(20, 120, 71, 31))
        self.exit_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_Button.setStyleSheet("QPushButton{\n"
"background-color:rgb(170, 0, 0);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(144, 0, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(121, 0, 0);\n"
"}\n"
"")
        self.exit_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_Button.setIcon(icon)
        self.exit_Button.setIconSize(QtCore.QSize(25, 25))
        self.exit_Button.setObjectName("exit_Button")
        self.deleteInfo_Button_2 = QtWidgets.QPushButton(Dialog)
        self.deleteInfo_Button_2.setGeometry(QtCore.QRect(50, 460, 161, 71))
        self.deleteInfo_Button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteInfo_Button_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(170, 0, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:;\n"
"    color: rgb(133, 181, 105);\n"
"}\n"
"")
        self.deleteInfo_Button_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteInfo_Button_2.setIcon(icon1)
        self.deleteInfo_Button_2.setIconSize(QtCore.QSize(57, 57))
        self.deleteInfo_Button_2.setObjectName("deleteInfo_Button_2")
        self.refreshInfo_Button = QtWidgets.QPushButton(Dialog)
        self.refreshInfo_Button.setGeometry(QtCore.QRect(250, 460, 161, 71))
        self.refreshInfo_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refreshInfo_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(214, 143, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:;\n"
"    color: rgb(133, 181, 105);\n"
"}\n"
"")
        self.refreshInfo_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshInfo_Button.setIcon(icon2)
        self.refreshInfo_Button.setIconSize(QtCore.QSize(57, 57))
        self.refreshInfo_Button.setObjectName("refreshInfo_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Completed Table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "NickName"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Surname"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Height"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Hair Color"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Eye Color"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Special Signs"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Citizenship"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Place of Birth"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Languages"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "Criminal Activity"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "Last Case"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "Birth"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "Alive/Dead"))
        self.textEdit_27.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">You have been granted access to the &quot;</span><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Completed</span><span style=\" font-size:11pt; color:#ffffff;\">&quot; table.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">You can view information about criminal groups, as well as transfer the detained persons to the &quot;Completed&quot; table, and remove the dead from the table</span></p></body></html>"))
        self.textEdit_28.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Remember, information theft is punishable by law</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
