# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 347)
        Dialog.setMinimumSize(QtCore.QSize(430, 347))
        Dialog.setMaximumSize(QtCore.QSize(430, 347))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 0, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(68, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Dialog.setPalette(palette)
        Dialog.setStyleSheet("background-color: rgb(68, 134, 255);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 221, 111))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid rgb(51, 100, 191);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.InterpolPicture = QtWidgets.QLabel(self.frame)
        self.InterpolPicture.setGeometry(QtCore.QRect(120, 10, 91, 91))
        self.InterpolPicture.setStyleSheet("/*border-radius: 30px;\n"
"")
        self.InterpolPicture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InterpolPicture.setText("")
        self.InterpolPicture.setPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/Interpol_main.jpg"))
        self.InterpolPicture.setScaledContents(True)
        self.InterpolPicture.setObjectName("InterpolPicture")
        self.UserPicture = QtWidgets.QLabel(self.frame)
        self.UserPicture.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.UserPicture.setText("")
        self.UserPicture.setPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/UserPicture.png"))
        self.UserPicture.setScaledContents(True)
        self.UserPicture.setObjectName("UserPicture")
        self.InterpolButton = QtWidgets.QPushButton(self.frame)
        self.InterpolButton.setGeometry(QtCore.QRect(120, 10, 91, 91))
        self.InterpolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InterpolButton.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;\n"
"")
        self.InterpolButton.setText("")
        self.InterpolButton.setObjectName("InterpolButton")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(110, 10, 1, 93))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.UserButton = QtWidgets.QPushButton(self.frame)
        self.UserButton.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.UserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserButton.setStyleSheet("background-color: transparent;\n"
"border-radius: 10px;\n"
"")
        self.UserButton.setText("")
        self.UserButton.setObjectName("UserButton")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 130, 221, 201))
        self.frame_2.setStyleSheet("QFrame{\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid rgb(51, 100, 191);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setStyleSheet("border-right-color: rgb(68, 133, 255);\n"
"border-top-color: rgb(60, 118, 225);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 101, 21))
        self.label_2.setStyleSheet("border-radius: 5px;\n"
"border-right-color: rgb(68, 133, 255);\n"
"border-top-color:   rgb(51, 100, 191);\n"
"border-left-color:  rgb(51, 100, 191);\n"
"border-bottom-color:  rgb(68, 133, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 141, 21))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_4.setStyleSheet("border-right-color: rgb(68, 133, 255);\n"
"border-top-color:   rgb(51, 100, 191);\n"
"border-left-color:  rgb(51, 100, 191);\n"
"border-bottom-color:   rgb(68, 133, 255);")
        self.label_4.setObjectName("label_4")
        self.counter_crime = QtWidgets.QLabel(self.frame_2)
        self.counter_crime.setGeometry(QtCore.QRect(170, 40, 31, 21))
        self.counter_crime.setStyleSheet("border-radius: 10px;\n"
"border-color: rgb(60, 118, 225);")
        self.counter_crime.setObjectName("counter_crime")
        self.counter_mafia = QtWidgets.QLabel(self.frame_2)
        self.counter_mafia.setGeometry(QtCore.QRect(170, 70, 31, 21))
        self.counter_mafia.setStyleSheet("border-radius: 10px;\n"
"border-color: rgb(60, 118, 225);")
        self.counter_mafia.setObjectName("counter_mafia")
        self.refresh_Button = QtWidgets.QPushButton(self.frame_2)
        self.refresh_Button.setGeometry(QtCore.QRect(20, 150, 181, 41))
        self.refresh_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_Button.setStyleSheet("QPushButton{\n"
"background-color:rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(71, 138, 255);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_Button.setIcon(icon)
        self.refresh_Button.setIconSize(QtCore.QSize(23, 23))
        self.refresh_Button.setObjectName("refresh_Button")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 141, 21))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_5.setStyleSheet("border-right-color: rgb(68, 133, 255);\n"
"border-top-color:   rgb(51, 100, 191);\n"
"border-left-color:  rgb(51, 100, 191);\n"
"border-bottom-color:   rgb(68, 133, 255);")
        self.label_5.setObjectName("label_5")
        self.counter_completed = QtWidgets.QLabel(self.frame_2)
        self.counter_completed.setGeometry(QtCore.QRect(170, 100, 31, 21))
        self.counter_completed.setStyleSheet("border-radius: 10px;\n"
"border-color: rgb(60, 118, 225);")
        self.counter_completed.setObjectName("counter_completed")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 195, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.CrimeTable_Button = QtWidgets.QPushButton(Dialog)
        self.CrimeTable_Button.setGeometry(QtCore.QRect(240, 140, 181, 31))
        self.CrimeTable_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CrimeTable_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(71, 138, 255);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.CrimeTable_Button.setObjectName("CrimeTable_Button")
        self.MafiaTable_Button = QtWidgets.QPushButton(Dialog)
        self.MafiaTable_Button.setGeometry(QtCore.QRect(240, 190, 181, 31))
        self.MafiaTable_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MafiaTable_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(71, 138, 255);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.MafiaTable_Button.setObjectName("MafiaTable_Button")
        self.CompletedTable_Button = QtWidgets.QPushButton(Dialog)
        self.CompletedTable_Button.setGeometry(QtCore.QRect(240, 240, 181, 31))
        self.CompletedTable_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CompletedTable_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(71, 138, 255);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.CompletedTable_Button.setObjectName("CompletedTable_Button")
        self.aboutWin_Button = QtWidgets.QPushButton(Dialog)
        self.aboutWin_Button.setGeometry(QtCore.QRect(250, 280, 71, 51))
        self.aboutWin_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aboutWin_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(214, 143, 0);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(188, 125, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color: rgb(171, 114, 0);\n"
"}\n"
"")
        self.aboutWin_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutWin_Button.setIcon(icon1)
        self.aboutWin_Button.setIconSize(QtCore.QSize(27, 27))
        self.aboutWin_Button.setObjectName("aboutWin_Button")
        self.exit_Button = QtWidgets.QPushButton(Dialog)
        self.exit_Button.setGeometry(QtCore.QRect(330, 280, 71, 51))
        self.exit_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_Button.setStyleSheet("QPushButton{\n"
"background-color:rgb(170, 0, 0);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(144, 0, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(121, 0, 0);\n"
"}\n"
"")
        self.exit_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_Button.setIcon(icon2)
        self.exit_Button.setIconSize(QtCore.QSize(27, 27))
        self.exit_Button.setObjectName("exit_Button")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(240, 20, 180, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(240, 50, 180, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(240, 80, 180, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(240, 110, 180, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.timeOfAuth_Label = QtWidgets.QLabel(Dialog)
        self.timeOfAuth_Label.setGeometry(QtCore.QRect(240, 92, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.timeOfAuth_Label.setFont(font)
        self.timeOfAuth_Label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.timeOfAuth_Label.setObjectName("timeOfAuth_Label")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(300, 30, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(420, 100, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(350, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Menu"))
        self.label.setText(_translate("Dialog", "Criminal group:"))
        self.label_2.setText(_translate("Dialog", "Number of entries:"))
        self.label_4.setText(_translate("Dialog", "Mafia group:"))
        self.counter_crime.setText(_translate("Dialog", "0"))
        self.counter_mafia.setText(_translate("Dialog", "0"))
        self.refresh_Button.setText(_translate("Dialog", "Refresh Information"))
        self.label_5.setText(_translate("Dialog", "Finished with the crimes:"))
        self.counter_completed.setText(_translate("Dialog", "0"))
        self.CrimeTable_Button.setText(_translate("Dialog", "Inforamtion about the Crime"))
        self.MafiaTable_Button.setText(_translate("Dialog", "Inforamtion about the Mafia"))
        self.CompletedTable_Button.setText(_translate("Dialog", "Inforamtion about the Completed"))
        self.timeOfAuth_Label.setText(_translate("Dialog", "Time of Authorization:"))
        self.label_6.setText(_translate("Dialog", "Clint"))
        self.label_7.setText(_translate("Dialog", "Eastwood"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
