# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interpol.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(347, 348)
        Dialog.setMinimumSize(QtCore.QSize(347, 348))
        Dialog.setMaximumSize(QtCore.QSize(347, 348))
        Dialog.setStyleSheet("background-color: rgb(68, 134, 255);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(210, 10, 121, 121))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid rgb(51, 100, 191);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/Interpol_main.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 191, 111))
        self.textEdit.setStyleSheet("border: 2px solid rgb(51, 100, 191);\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 140, 321, 71))
        self.textEdit_2.setStyleSheet("border: 2px solid white;\n"
"border-top-color: rgb(51, 100, 191);\n"
"\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 230, 321, 71))
        self.textEdit_3.setStyleSheet("border: 2px solid rgb(51, 100, 191);\n"
"border-top-color: white;\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.exit_Button = QtWidgets.QPushButton(Dialog)
        self.exit_Button.setGeometry(QtCore.QRect(250, 310, 71, 31))
        self.exit_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_Button.setStyleSheet("QPushButton{\n"
"background-color:rgb(170, 0, 0);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(144, 0, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(121, 0, 0);\n"
"}\n"
"")
        self.exit_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_Button.setIcon(icon)
        self.exit_Button.setIconSize(QtCore.QSize(20, 20))
        self.exit_Button.setObjectName("exit_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Interpol"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Membership:    <span style=\" font-weight:600;\">194 countries</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Headquarters: <span style=\" font-weight:600;\">France, Lyon</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Created:          <span style=\" font-weight:600;\">1923</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Number of employees: <span style=\" font-weight:600;\">819 people</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">-----------------------------------</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">President: <span style=\" font-weight:600;\">Ahmed Nasser Al-Raisi</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">General Secretary: <span style=\" font-weight:600;\">Jurgen Stock</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Type of organization: <span style=\" font-weight:600;\">international intergovernmental organization</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Official languages: <span style=\" font-weight:600;\">English, French, Spanish, Arabic</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Website: <a href=\"http://www.interpol.int/\"><span style=\" font-family:\'sans-serif\'; font-size:8pt; text-decoration: underline; color:#ffffff;\">interpol.int</span></a></p></body></html>"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">History</span>:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In 1914, with the active participation of Prince Albert I of Monaco, the 1st International Criminal Police Congress was held in the Principality, which was attended by police officers from 14 countries (including the Russian Empire). The Congress approved the initiative to create an international criminal police commission, but the First World War prevented the execution of plans.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The re-establishment of Interpol took place only in 1946 with the relocation of the headquarters to Paris. The current charter was adopted in 1956. He also approved the new name of the organization - &quot;International Criminal Police Organization — Interpol&quot;.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
