# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MafiaTable1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1212, 758)
        Dialog.setMinimumSize(QtCore.QSize(1212, 758))
        Dialog.setMaximumSize(QtCore.QSize(1212, 758))
        Dialog.setStyleSheet("background-color: rgb(68, 134, 255);")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 1161, 421))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(127)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 480, 691, 251))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid rgb(51, 100, 191);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CriminalActivity_Label = QtWidgets.QTextEdit(self.frame)
        self.CriminalActivity_Label.setGeometry(QtCore.QRect(370, 160, 161, 31))
        self.CriminalActivity_Label.setObjectName("CriminalActivity_Label")
        self.Birth_Label = QtWidgets.QTextEdit(self.frame)
        self.Birth_Label.setGeometry(QtCore.QRect(370, 210, 161, 31))
        self.Birth_Label.setObjectName("Birth_Label")
        self.LastCase_Label = QtWidgets.QTextEdit(self.frame)
        self.LastCase_Label.setGeometry(QtCore.QRect(370, 60, 161, 81))
        self.LastCase_Label.setObjectName("LastCase_Label")
        self.PlaceOfBirth_Label = QtWidgets.QTextEdit(self.frame)
        self.PlaceOfBirth_Label.setGeometry(QtCore.QRect(190, 210, 161, 31))
        self.PlaceOfBirth_Label.setObjectName("PlaceOfBirth_Label")
        self.Languages_Label = QtWidgets.QTextEdit(self.frame)
        self.Languages_Label.setGeometry(QtCore.QRect(370, 10, 161, 31))
        self.Languages_Label.setObjectName("Languages_Label")
        self.Citizenship_Label = QtWidgets.QTextEdit(self.frame)
        self.Citizenship_Label.setGeometry(QtCore.QRect(190, 160, 161, 31))
        self.Citizenship_Label.setObjectName("Citizenship_Label")
        self.SpecialSigns_Label = QtWidgets.QTextEdit(self.frame)
        self.SpecialSigns_Label.setGeometry(QtCore.QRect(190, 60, 161, 81))
        self.SpecialSigns_Label.setObjectName("SpecialSigns_Label")
        self.EyeColor_Label = QtWidgets.QTextEdit(self.frame)
        self.EyeColor_Label.setGeometry(QtCore.QRect(190, 10, 161, 31))
        self.EyeColor_Label.setObjectName("EyeColor_Label")
        self.NickName_Label = QtWidgets.QTextEdit(self.frame)
        self.NickName_Label.setGeometry(QtCore.QRect(10, 60, 161, 31))
        self.NickName_Label.setObjectName("NickName_Label")
        self.Height_Label = QtWidgets.QTextEdit(self.frame)
        self.Height_Label.setGeometry(QtCore.QRect(10, 160, 161, 31))
        self.Height_Label.setObjectName("Height_Label")
        self.Sername_Label = QtWidgets.QTextEdit(self.frame)
        self.Sername_Label.setGeometry(QtCore.QRect(10, 110, 161, 31))
        self.Sername_Label.setObjectName("Sername_Label")
        self.HairColor_Label = QtWidgets.QTextEdit(self.frame)
        self.HairColor_Label.setGeometry(QtCore.QRect(10, 210, 161, 31))
        self.HairColor_Label.setObjectName("HairColor_Label")
        self.Name_Label = QtWidgets.QTextEdit(self.frame)
        self.Name_Label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.Name_Label.setObjectName("Name_Label")
        self.addInfo_Button = QtWidgets.QPushButton(self.frame)
        self.addInfo_Button.setGeometry(QtCore.QRect(550, 160, 121, 81))
        self.addInfo_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addInfo_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:;\n"
"    color: rgb(133, 181, 105);\n"
"}\n"
"")
        self.addInfo_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addInfo_Button.setIcon(icon)
        self.addInfo_Button.setIconSize(QtCore.QSize(64, 64))
        self.addInfo_Button.setObjectName("addInfo_Button")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(550, 20, 118, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(550, 40, 118, 1))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(550, 60, 118, 1))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(550, 80, 118, 1))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(550, 100, 118, 1))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(550, 120, 118, 1))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(550, 140, 118, 1))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.name_sortButton = QtWidgets.QPushButton(self.frame)
        self.name_sortButton.setGeometry(QtCore.QRect(150, 10, 20, 31))
        self.name_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.name_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.name_sortButton.setText("")
        self.name_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.name_sortButton.setObjectName("name_sortButton")
        self.NickName_sortButton = QtWidgets.QPushButton(self.frame)
        self.NickName_sortButton.setGeometry(QtCore.QRect(150, 60, 20, 31))
        self.NickName_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NickName_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.NickName_sortButton.setText("")
        self.NickName_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.NickName_sortButton.setObjectName("NickName_sortButton")
        self.surname_sortButton = QtWidgets.QPushButton(self.frame)
        self.surname_sortButton.setGeometry(QtCore.QRect(150, 110, 20, 31))
        self.surname_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.surname_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.surname_sortButton.setText("")
        self.surname_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.surname_sortButton.setObjectName("surname_sortButton")
        self.height_sortButton = QtWidgets.QPushButton(self.frame)
        self.height_sortButton.setGeometry(QtCore.QRect(150, 160, 20, 31))
        self.height_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.height_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.height_sortButton.setText("")
        self.height_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.height_sortButton.setObjectName("height_sortButton")
        self.haircolor_sortButton = QtWidgets.QPushButton(self.frame)
        self.haircolor_sortButton.setGeometry(QtCore.QRect(150, 210, 20, 31))
        self.haircolor_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.haircolor_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.haircolor_sortButton.setText("")
        self.haircolor_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.haircolor_sortButton.setObjectName("haircolor_sortButton")
        self.eyecolor_sortButton = QtWidgets.QPushButton(self.frame)
        self.eyecolor_sortButton.setGeometry(QtCore.QRect(330, 10, 20, 31))
        self.eyecolor_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eyecolor_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.eyecolor_sortButton.setText("")
        self.eyecolor_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.eyecolor_sortButton.setObjectName("eyecolor_sortButton")
        self.specialSigns_sortButton = QtWidgets.QPushButton(self.frame)
        self.specialSigns_sortButton.setGeometry(QtCore.QRect(330, 60, 20, 81))
        self.specialSigns_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.specialSigns_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.specialSigns_sortButton.setText("")
        self.specialSigns_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.specialSigns_sortButton.setObjectName("specialSigns_sortButton")
        self.Citizenship_sortButton = QtWidgets.QPushButton(self.frame)
        self.Citizenship_sortButton.setGeometry(QtCore.QRect(330, 160, 20, 31))
        self.Citizenship_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Citizenship_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.Citizenship_sortButton.setText("")
        self.Citizenship_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.Citizenship_sortButton.setObjectName("Citizenship_sortButton")
        self.placeOfBirth_sortButton = QtWidgets.QPushButton(self.frame)
        self.placeOfBirth_sortButton.setGeometry(QtCore.QRect(330, 210, 20, 31))
        self.placeOfBirth_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.placeOfBirth_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.placeOfBirth_sortButton.setText("")
        self.placeOfBirth_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.placeOfBirth_sortButton.setObjectName("placeOfBirth_sortButton")
        self.languages_sortButton = QtWidgets.QPushButton(self.frame)
        self.languages_sortButton.setGeometry(QtCore.QRect(510, 10, 20, 31))
        self.languages_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.languages_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.languages_sortButton.setText("")
        self.languages_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.languages_sortButton.setObjectName("languages_sortButton")
        self.lastCase_sortButton = QtWidgets.QPushButton(self.frame)
        self.lastCase_sortButton.setGeometry(QtCore.QRect(510, 60, 20, 81))
        self.lastCase_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lastCase_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.lastCase_sortButton.setText("")
        self.lastCase_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.lastCase_sortButton.setObjectName("lastCase_sortButton")
        self.crimincalActivity_sortButton = QtWidgets.QPushButton(self.frame)
        self.crimincalActivity_sortButton.setGeometry(QtCore.QRect(510, 160, 20, 31))
        self.crimincalActivity_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crimincalActivity_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.crimincalActivity_sortButton.setText("")
        self.crimincalActivity_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.crimincalActivity_sortButton.setObjectName("crimincalActivity_sortButton")
        self.birth_sortButton = QtWidgets.QPushButton(self.frame)
        self.birth_sortButton.setGeometry(QtCore.QRect(510, 210, 20, 31))
        self.birth_sortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.birth_sortButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(38, 75, 143);\n"
"}\n"
"")
        self.birth_sortButton.setText("")
        self.birth_sortButton.setIconSize(QtCore.QSize(64, 64))
        self.birth_sortButton.setObjectName("birth_sortButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 460, 1191, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(730, 560, 451, 161))
        self.frame_2.setStyleSheet("background-color: rgb(51, 100, 191);\n"
"border: 5px;\n"
"border-color: rgb(51, 100, 191);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textEdit_27 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_27.setGeometry(QtCore.QRect(10, 10, 431, 101))
        self.textEdit_27.setStyleSheet("border: 2px solid rgb(228, 232, 235);\n"
"border-left-color: rgb(85, 170, 255);\n"
"border-bottom-color: rgb(85, 170, 255);\n"
"\n"
"\n"
"")
        self.textEdit_27.setObjectName("textEdit_27")
        self.textEdit_28 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_28.setGeometry(QtCore.QRect(110, 120, 331, 31))
        self.textEdit_28.setStyleSheet("border: 2px solid rgb(51, 100, 191);\n"
"border-top-color:  rgb(85, 170, 255);\n"
"border-right-color: rgb(228, 232, 235);\n"
"border-left-color:  rgb(85, 170, 255);\n"
"border-bottom-color: rgb(228, 232, 235);\n"
"\n"
"")
        self.textEdit_28.setObjectName("textEdit_28")
        self.exit_Button = QtWidgets.QPushButton(self.frame_2)
        self.exit_Button.setGeometry(QtCore.QRect(20, 120, 71, 31))
        self.exit_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_Button.setStyleSheet("QPushButton{\n"
"background-color:rgb(170, 0, 0);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(144, 0, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:rgb(121, 0, 0);\n"
"}\n"
"")
        self.exit_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_Button.setIcon(icon1)
        self.exit_Button.setIconSize(QtCore.QSize(25, 25))
        self.exit_Button.setObjectName("exit_Button")
        self.deleteInfo_Button = QtWidgets.QPushButton(Dialog)
        self.deleteInfo_Button.setGeometry(QtCore.QRect(730, 480, 121, 71))
        self.deleteInfo_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteInfo_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(170, 0, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:;\n"
"    color: rgb(133, 181, 105);\n"
"}\n"
"")
        self.deleteInfo_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteInfo_Button.setIcon(icon2)
        self.deleteInfo_Button.setIconSize(QtCore.QSize(57, 57))
        self.deleteInfo_Button.setObjectName("deleteInfo_Button")
        self.refreshInfo_Button = QtWidgets.QPushButton(Dialog)
        self.refreshInfo_Button.setGeometry(QtCore.QRect(1050, 480, 121, 71))
        self.refreshInfo_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refreshInfo_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(214, 143, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:;\n"
"    color: rgb(133, 181, 105);\n"
"}\n"
"")
        self.refreshInfo_Button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshInfo_Button.setIcon(icon3)
        self.refreshInfo_Button.setIconSize(QtCore.QSize(57, 57))
        self.refreshInfo_Button.setObjectName("refreshInfo_Button")
        self.deleteInfo_Button_2 = QtWidgets.QPushButton(Dialog)
        self.deleteInfo_Button_2.setGeometry(QtCore.QRect(870, 480, 161, 71))
        self.deleteInfo_Button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteInfo_Button_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(51, 100, 191);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(170, 0, 0);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:;\n"
"    color: rgb(133, 181, 105);\n"
"}\n"
"")
        self.deleteInfo_Button_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteInfo_Button_2.setIcon(icon4)
        self.deleteInfo_Button_2.setIconSize(QtCore.QSize(57, 57))
        self.deleteInfo_Button_2.setObjectName("deleteInfo_Button_2")
        self.frame.raise_()
        self.tableWidget.raise_()
        self.line.raise_()
        self.frame_2.raise_()
        self.deleteInfo_Button.raise_()
        self.refreshInfo_Button.raise_()
        self.deleteInfo_Button_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mafia Table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "NickName"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Surname"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Height"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Hair Color"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Eye Color"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Special Signs"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Citizenship"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Place of Birth"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Languages"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "Criminal Activity"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "Last Case"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "Birth"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "Alive/Dead"))
        self.CriminalActivity_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Criminal Activity</span></p></body></html>"))
        self.Birth_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Birth</span></p></body></html>"))
        self.LastCase_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Last Case</span></p></body></html>"))
        self.PlaceOfBirth_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Place of Birth</span></p></body></html>"))
        self.Languages_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Languages</span></p></body></html>"))
        self.Citizenship_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Citizenship</span></p></body></html>"))
        self.SpecialSigns_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Special Signs</span></p></body></html>"))
        self.EyeColor_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Eye Color</span></p></body></html>"))
        self.NickName_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">NickName</span></p></body></html>"))
        self.Height_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Height</span></p></body></html>"))
        self.Sername_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Surname</span></p></body></html>"))
        self.HairColor_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Hair Color</span></p></body></html>"))
        self.Name_Label.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Name</span></p></body></html>"))
        self.textEdit_27.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">You have been granted access to the &quot;</span><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Mafia</span><span style=\" font-size:11pt; color:#ffffff;\">&quot; table.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">You can view information about criminal groups, as well as transfer the detained persons to the &quot;Completed&quot; table, and remove the dead from the table</span></p></body></html>"))
        self.textEdit_28.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Remember, information theft is punishable by law</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
