# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoAboutMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 216)
        Dialog.setMinimumSize(QtCore.QSize(444, 216))
        Dialog.setMaximumSize(QtCore.QSize(444, 216))
        Dialog.setStyleSheet("background-color: rgb(68, 134, 255);")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(9, 9, 421, 161))
        self.frame_2.setStyleSheet("background-color: rgb(51, 100, 191);\n"
"border: 5px;\n"
"border-color: rgb(51, 100, 191);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 81))
        self.label.setStyleSheet("border-radius: 10px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForInfoAboutMenu.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(10, 10, 101, 101))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius: 10px;\n"
"background-color: rgb(105, 147, 63);\n"
"border: 2px solid rgb(51, 100, 191);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(120, 10, 281, 101))
        self.textEdit.setStyleSheet("border: 2px solid rgb(228, 232, 235);\n"
"border-left-color:rgb(136, 191, 84);\n"
"border-bottom-color:rgb(136, 191, 84);\n"
"\n"
"\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_2.setGeometry(QtCore.QRect(13, 120, 391, 31))
        self.textEdit_2.setStyleSheet("border: 2px solid rgb(51, 100, 191);\n"
"border-top-color: rgb(136, 191, 84);\n"
"border-right-color: rgb(228, 232, 235);\n"
"border-left-color: rgb(136, 191, 84);\n"
"border-bottom-color: rgb(228, 232, 235);\n"
"\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.frame.raise_()
        self.label.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.exit_Button = QtWidgets.QPushButton(Dialog)
        self.exit_Button.setGeometry(QtCore.QRect(30, 180, 71, 31))
        self.exit_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_Button.setStyleSheet("QPushButton{\n"
"background-color:rgb(105, 147, 63);\n"
"border-radius: 10px;\n"
"} \n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(118, 165, 70);\n"
" }\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"padding-top: 3px;\n"
" background-color:;\n"
"    color: rgb(133, 181, 105);\n"
"}\n"
"")
        self.exit_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Python projects/PicturesForApps/picForButton6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_Button.setIcon(icon)
        self.exit_Button.setIconSize(QtCore.QSize(23, 23))
        self.exit_Button.setObjectName("exit_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Information About Menu"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ffffff;\">You have been granted access to the Interpol database.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ffffff;\">You can view information about Criminal and Mafia groups, as well as transfer detained persons to the &quot;Completed&quot; table</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Remember, information theft is punishable by law</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
